import { StyleSheet } from 'react-native';

export const modalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
  },
  headerRightPlaceholder: {
    width: 60,
  },
  cancel: {
    color: '#000',
    fontSize: 16,
  },
  disabledText: {
    color: '#ccc',
  },
  title: {
    color: '#000',
    fontSize: 16,
    fontWeight: '600',
  },
  list: {
    flex: 1,
    backgroundColor: '#eee',
  },
  threadContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 12,
    backgroundColor: 'transparent',
  },
  avatarContainer: {
    alignItems: 'center',
    marginRight: 12,
    paddingTop: 2,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#555',
  },
  avatarSmall: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#555',
  },
  threadLine: {
    width: 1.5,
    flexGrow: 1,
    backgroundColor: '#aaa',
    marginTop: 8,
  },
  contentContainer: {
    flex: 1,
    paddingBottom: 6,
    position: 'relative',
  },
  userInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 2,
  },
  username: {
    fontWeight: '600',
    fontSize: 15,
    color: '#000',
  },
  input: {
    fontSize: 15,
    color: '#000',
    paddingTop: 4,
    paddingBottom: 8,
    minHeight: 24,
    lineHeight: 20,
  },
  actionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  actionButton: {
    marginRight: 15,
  },
  imageFlatList: {
    marginTop: 12,
    marginBottom: 4,
  },
  imagePreviewContainer: {
    position: 'relative',
    marginRight: 8,
    width: 100,
    height: 100,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#f0f0f0',
  },
  imagePreview: {
    width: '100%',
    height: '100%',
  },
  removeImageButton: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 12,
    padding: 2,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingTop: 10,
    backgroundColor: '#fff',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  footerText: {
    color: '#8e8e93',
    fontSize: 14,
  },
  postButton: {
    paddingVertical: 8,
    paddingHorizontal: 18,
    backgroundColor: '#000',
    borderRadius: 18,
  },
  postButtonDisabled: {
    backgroundColor: '#ccc',
  },
  postButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  dropdownContainer: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginHorizontal: 10,
    overflow: 'hidden',
    marginBottom: 5,
  },
  dropdownOption: {
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#e5e5e5',
  },
  selectedOption: {},
  dropdownOptionText: {
    fontSize: 16,
    color: '#000',
  },
  selectedOptionText: {
    fontWeight: '600',
    color: '#007AFF',
  },
  removeButton: {
    padding: 4,
    marginRight: -4,
    marginLeft: 8,
  },
  listFooter: {
    paddingLeft: 26,
    paddingTop: 10,
    flexDirection: 'row',
  },
  listFooterAvatar: {
    marginRight: 20,
    paddingTop: 2,
  },
  locationContainer: {
    marginTop: 4,
    marginBottom: 4,
  },
  locationText: {
    fontSize: 14,
    color: '#8e8e93',
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  topicContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    flex: 1,
  },
  topicInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topicText: {
    fontSize: 15,
    fontWeight: 600,
    color: '#000',
  },
  topicPlaceholder: {
    fontWeight: 400,
  },
  hiddenPlaceholder: {
    opacity: 0,
  },
  chevronIcon: {
    marginHorizontal: 2,
    alignSelf: 'center',
  },
  topicInputSection: {
    marginBottom: 8,
  },
  topicTextInput: {
    borderWidth: 1,
    borderColor: '#e5e5e5',
    borderRadius: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    color: '#000',
    backgroundColor: '#fff',
  },
  topicOption: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    backgroundColor: '#fff',
    marginBottom: 1,
    minHeight: 44,
    gap: 2,
  },
  topicOptionText: {
    fontSize: 16,
    color: '#000',
    flex: 1,
  },
  newTopicText: {
    fontSize: 13,
    color: '#999',
  },
  topicSelectionOverlay: {
    position: 'absolute',
    top: 50,
    left: 0,
    right: 0,
    zIndex: 1000,
    elevation: 10,
  },
  topicSelectionContent: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    marginHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  topicOptionsList: {
    maxHeight: 150,
    marginTop: 8,
    flexGrow: 0,
  },
  // Bottom Sheet Styles
  bottomSheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  bottomSheetContainer: {
    flex: 1,
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  bottomSheetHeaderLine: {
    width: 40,
    height: 2,
    backgroundColor: '#ccc',
    borderRadius: 2,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 15,
    marginVertical: 8,
    paddingHorizontal: 12,
    paddingVertical: 3,
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
  },
  searchInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#000',
  },
  removeSearchTextButton: {
    padding: 4,
    marginLeft: 8,
  },
  currentTopicContainer: {
    paddingHorizontal: 20,
  },
  currentTopicChip: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f5f5f5',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderRadius: 20,
  },
  currentTopicText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '400',
    marginRight: 8,
  },
  removeTopicButton: {
    padding: 2,
  },
  bottomSheetList: {
    flex: 1,
    paddingBottom: 40,
  },
  selectedTopicOption: {
    backgroundColor: '#f0f8ff',
  },
  selectedTopicText: {
    color: '#007AFF',
    fontWeight: '500',
  },
  newTopicIcon: {
    marginLeft: 8,
  },
});
